apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-bridge-config
  labels:
    app: mqtt-bridge
data:
  application.properties: |
    #Bridge related settings
    bridge.id=my-bridge

    #MQTT server common
    mqtt.host=0.0.0.0
    mqtt.port=1883
    #Apache Kafka common
    kafka.bootstrap.servers=<kafka-bootstrap-servers>
  topic-mapping-rules.json: '[]'
  log4j2.properties: |
    name=MqttBridgeConfig
    appender.console.type=Console
    appender.console.name=STDOUT
    appender.console.layout.type=PatternLayout
    appender.console.layout.pattern=%d{yyyy-MM-dd HH:mm:ss} %-5p [%t] %c{1}:%L - %m%n
    rootLogger.level=INFO
    rootLogger.appenderRefs=console
    rootLogger.appenderRef.console.ref=STDOUT
    rootLogger.additivity=false
    logger.bridge.name=io.strimzi.kafka.bridge.mqtt
    logger.bridge.level=INFO
    logger.bridge.appenderRefs=console
    logger.bridge.appenderRef.console.ref=STDOUT
    logger.bridge.additivity=false