#Bridge related settings
bridge.id=my-bridge
bridge.topic.default=default_topic
#MQTT server common
mqtt.host=0.0.0.0
mqtt.port=1883
mqtt.max.bytes.message=8092
#MQTT server SSL/TLS (optional)
#mqtt.ssl.enable=true
#mqtt.ssl.certificate.location=path/to/certificate.crt
#mqtt.ssl.key.location=path/to/private.key
#mqtt.ssl.certificate=--BEGIN CERTIFICATE--\n...\n--END CERTIFICATE--
#mqtt.ssl.key=--BEGIN PRIVATE KEY--\n...\n--END PRIVATE KEY--
#mqtt.ssl.enabled.protocols=TLSv1.2,TLSv1.3
#mqtt.ssl.enabled.cipher.suites=TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384

#Apache Kafka common
kafka.bootstrap.servers=localhost:9092
