apiVersion: v1
kind: Service
metadata:
  name: mqtt-bridge
  labels:
    app: mqtt-bridge
spec:
  selector:
    app: mqtt-bridge
  ports:
      - name: mqtt
        protocol: TCP
        port: 1883
        targetPort: 1883
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
